### ISSUE TITLE
Desktop app doesn't work - Upgrade Room Version

### ISSUE THREAD

**Issue by minihub19** [SchildiChat/schildichat-desktop#214] opened 2023-10-15 19:26 UTC
Hi,
I've installed and reinstalled SchildiChat for Windows desktop several times now. And each time I get an error that I need to upgrade the room. It won't load my chats or connect or allow me to see my backups in settings... when I select Help and About in settings, it just gets me out of settings.
I don't have this issue with Element desktop. 

![Screenshot 2023-10-15 215737](https://github.com/SchildiChat/schildichat-desktop/assets/148008275/8390f53b-5f29-4f4c-9581-e242813c096b)

![Screenshot 2023-10-15 215932](https://github.com/SchildiChat/schildichat-desktop/assets/148008275/b39caf39-19de-4bef-8fd9-b5951c7b6c2c)

![Screenshot 2023-10-15 220020](https://github.com/SchildiChat/schildichat-desktop/assets/148008275/2a037637-f711-4543-82d9-f6d09e83f08d)

![image](https://github.com/SchildiChat/schildichat-desktop/assets/148008275/53015654-5bb1-4d5f-8d74-4d6a15061c9f)
I've only ever attempted to install the latest version.

**Comment by su-ex** [comment] 2023-10-15 20:17
Duplicate of https://github.com/SchildiChat/schildichat-desktop/issues/170

**Closed by su-ex** 2023-10-15 20:17 UTC
