### ISSUE TITLE
Every start of desktop app I need to log in again

### ISSUE THREAD

**Issue by DubbaThony** [SchildiChat/schildichat-desktop#227] opened 2024-01-01 17:32 UTC
Possibly related with #170 

Whenever I open the app, it will show me "Connection to the server was lost" message (might not be literally, app is in my local language, this is translated back).
This happens consistently since I started using Schildi on windows. This does not happen on android version.
To make it work, I need to log out and log back in, do the setup with android (scanning qr) and wait for keys to sync.
After re-logging as long as I don't quit the app the connection stays up indefinitely (max tried 3 months, my system is fairly high uptime - therefore it doesn't look like exactly #170 but still might be related)

What's more, in that disconnected state, Im unable to enter settings -> about.

While in that state, in console it looks like it's calling the server without token and getting 401's, but actually it sends authorization header, but it's clearly wrong:
`authorization: Bearer [object Object]`

I looked deeper and it seems that when `authedRequest()` is called, it uses `this.opts.accessToken` for header.
This has actually value that looks like AES encrypted or something similar, it's object with `ciphertext`, `iv` and `mac` fields.

That's all I know.

Other context:
**Version**: SchildiChat: 1.11.30-sc.2 Olm version: 3.2.12
**OS**: Windows 10 (2021; 10.0.19044.3803)
This does not happen on Element (which I have side by side for different matrix server).

**Comment by RazerStvH** [comment] 2024-05-23 05:24
Same problem. I can use SchildiChat on Android and Linux, but i can't use it on Windows.

**Comment by TheStagnation** [comment] 2024-06-19 04:25
Same problem. 
Windows 10 Home
SchildiChat version: 1.11.36-sc.3
Olm version: 3.2.14

**Comment by C6OI** [comment] 2024-09-15 06:34
Same
![image](https://github.com/user-attachments/assets/3d78b0d5-3df3-4144-8ef6-a4e825d06711)

**Comment by su-ex** [comment] 2024-09-15 06:39
Duplicate of #170

**Closed by su-ex** 2024-09-15 06:39 UTC
